### ISSUE TITLE
How to add a new network

### ISSUE THREAD

**Issue by Piquinikis** [gnosis/gnosis-py#173]
Hi team! 

How is the workflow to add a new network information into this repo?

Regards!

**Comment by datradito** [comment]
We want to add Evmos Testnet/Mainnet:

Mainnet ChainID = 9001
Testnet ChainID = 9000

CC: @Uxio0

**Comment by Uxio0** [comment]
Hi, you need to add it here https://github.com/gnosis/gnosis-py/blob/master/gnosis/eth/ethereum_network.py and make sure it's present on https://github.com/ethereum-lists/chains (I see it is)

**Comment by Piquinikis** [comment]
Perfect, I sent the PR and it was approved and merged as well. 
I need to upgrade the tag version or do we continue working from the master branch? If it's needed to upgrade the version, how I can do this?

**Comment by Uxio0** [comment]
You will have to wait for the next release 😉

**Comment by Piquinikis** [comment]
Perfect! Thank you very much!

**Comment by Uxio0** [comment]
Thank you!
