### ISSUE TITLE
Building wheel for coincurve (PEP 517) ... error

### ISSUE THREAD

**Issue by pythonster** [gnosis/gnosis-py#24]
i tried gnosis 2.5,2.6,latest via ```pip install gnosis-py```, ```pip install gnosis-py --no-binary :all:```, ```python -m pip install --no-use-pep517 gnosis-py``` with pip 20. and 18. over the python 3.6, 3.7, 3.8

**Comment by Uxio0** [comment]
Hi @pythonster, that's not an issue related to `gnosis-py`, you might be lacking some required libraries to build coincurve, more info https://github.com/ofek/coincurve#installation

I added the instructions to the README in case someone has the same issue, thanks for reaching us!
