### ISSUE TITLE
Compatibility with 1.2.0 and above

### ISSUE THREAD

**Issue by yufengshen** [gnosis/gnosis-py#34]
I noticed current code has many condition switch on version 1.1.1 & 1.0.0, e.g.

https://github.com/gnosis/gnosis-py/blob/e4616bffa9545afae60b3be4ce89c4c60f987b68/gnosis/safe/safe_create2_tx.py#L59

https://github.com/gnosis/gnosis-py/blob/e4616bffa9545afae60b3be4ce89c4c60f987b68/gnosis/safe/safe_create2_tx.py#L212

If 1.2.0 is actually compatible with 1.1.1, then can we make the condition switch to be 
if (version == 1.0.0) {

} else {

}

**Comment by Uxio0** [comment]
Creation of new Safes is a very delicated process, and doing it it wrong could make user funds to be stuck, so for example for the case you link `1.1.1` has a different setup than `1.0.0`, and for example for the new `1.3.0` contracts we will use a different `fallbackHandler` by default, o I prefer to raise an error in case the deployment is not tested than just use an `else`. Does that sound reasonable? 🙂

**Comment by yufengshen** [comment]
Sure; my case is that I want to use Safes on Heco which is not officially supported by Gnosis yet, so I have to use
the toolchain to create personal Safes on Heco and noticed that 1.2.0 is not working with the toolchain; but no big
deal for me, I can just tweek the particular part of the condition switch on versions; If the toolchain could catch up
with the 1.2.0/1.3.0 that would be great.

**Comment by Uxio0** [comment]
> Sure; my case is that I want to use Safes on Heco which is not officially supported by Gnosis yet, so I have to use
> the toolchain to create personal Safes on Heco and noticed that 1.2.0 is not working with the toolchain; but no big
> deal for me, I can just tweek the particular part of the condition switch on versions; If the toolchain could catch up
> with the 1.2.0/1.3.0 that would be great.

Thanks for noticing, but the parts of the code you are talking about are the ones used by the relay service. If you want to deploy contracts in another network you can do easily, take a look at https://github.com/gnosis/safe-cli/blob/master/safe_creator.py which is deploying safe contract v1.2.0 and I will update it soon to deploy v1.3.0

**Comment by yufengshen** [comment]
Great, I saw that in the commit 
safe_contract = get_safe_V1_3_0_contract(ethereum_client.w3, safe_contract_address)
it now calls the V1_3_0 contract::setup func directly instead of relying on gnosis.safe lib (so I assume 1.2.0 is mostly compatible with v1.3.0)

thanks for the quick response;

**Comment by Uxio0** [comment]
> 1.2.0 is mostly compatible with v1.3.0

Yes, and for new deployments is the recommended now, you can check the audits: https://github.com/gnosis/safe-contracts/blob/v1.3.0/docs/audit_1_3_0.md

Have a good day
