### ISSUE TITLE
No more transaction_formatter in web3/_utils/method_formatters.py

### ISSUE THREAD

**Issue by NikZak** [gnosis/gnosis-py#49]
https://github.com/gnosis/gnosis-py/blob/21ffe4c835b127de8d328e9ba1cb72b2317db004/gnosis/eth/ethereum_client.py#L19

I believe  ``transaction_formatter`` in ``web3._utils.method_formatters`` was replaced with ``transaction_result_formatter`` for the purpose of EIP 1559 support

**Comment by Uxio0** [comment]
Thanks, fixed here https://github.com/gnosis/gnosis-py/pull/43
