### ISSUE TITLE
Why eth-abi2

### ISSUE THREAD

**Issue by pipermerriam** [gnosis/gnosis-py#9]
We (the SnakeCharmers) are curious why `eth-abi2` exists and if there's a missing feature in `eth-abi` that you needed?

**Comment by Uxio0** [comment]
Hi @pipermerriam, yes, I was missing the `encode_abi_packed` and `encode_single_packed`. As at that time web3.py depended on `eth_abi<2` I had to create a new package.

I have just updated the library to use `web3 v5` (nice work on that big update, I was looking forward to updating but didn't have enough time to do so testing everything carefully) so I removed the `eth_abi2` dependency d38fe749eea817f78daa7f8cad544027199b42e4

**Comment by Uxio0** [comment]
Good to know. @pipermerriam let me know if you need something else, I'm closing this issue for now. Btw, I loved your Trinity talk at devcon 4 :)
